version: '3.8'

services:
  web:
    build: .
    container_name: org_management_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    external: true